Feature/finish user
BerndtMaciej/expert-in-action pull request #2
Opened 2020-04-21 22:25 UTC by BerndtMaciej

zakres zmiany:
-dodanie możliwość aktualizowania danych użytkownika
-naprawa błędów przy rejestracji użytkownika

2020-04-22 19:20 UTC, mszupke requested changes
Kilka drobnych uwag

2020-04-22 19:20 UTC, mszupke commented on src/main/java/com/sdaacademy/expert_in_action/controller/UserController.java
> +
Dobrze rozumiem, że API umożliwia na pobranie hasła dla wskazanego użytkownika?

2020-04-22 19:20 UTC, mszupke commented on src/main/java/com/sdaacademy/expert_in_action/service/UserService.java
>      public Optional<User> getUserById(UUID user_id) {
Konwencja nazewnicza parametrów w Javie mówi aby używać sposobu camelCase

2020-04-22 19:20 UTC, mszupke commented on src/main/java/com/sdaacademy/expert_in_action/service/UserService.java
> +                userRepositor.findAll().stream().anyMatch(u -> u.getLogin().equals(user.getLogin()))) {
Dlaczego nie skorzystałeś z metod 
userRepository.findUserByLogin I userRepository.FindUserByEmail?

2020-04-22 19:20 UTC, mszupke commented on src/main/java/com/sdaacademy/expert_in_action/service/UserService.java
>              user.setUserId(UUID.randomUUID());
Nie musisz nadawać id. Baza danych się tym zajmie

2020-04-22 19:20 UTC, mszupke commented on src/main/java/com/sdaacademy/expert_in_action/service/UserService.java
> +            password1.setPasswordId(UUID.randomUUID());
Nie musisz nadawać id. Baza danych się tym zajmie

2020-04-22 19:20 UTC, mszupke commented on src/main/java/com/sdaacademy/expert_in_action/service/UserService.java
> +                    password1.setPasswordId(UUID.randomUUID());
Nie musisz nadawać id. Baza danych się tym zajmie

2020-04-22 21:59 UTC, BerndtMaciej commented on src/main/java/com/sdaacademy/expert_in_action/controller/UserController.java
> +
Metoda ta zwraca historie wszystkich użytych haseł przez użytkownika i została zaimplementowana żeby ułatwić mi testowanie API, sprawdzania poprawności implementacji metod służących do zmiany hasła. W następnych wersjach sytemu metoda ta zostanie usunięta.

2020-04-24 18:35 UTC, mszupke-sda approved these changes
ok

2020-04-25 07:21 UTC, merged